/Rich/radiator/reset
/Rich/pmt/qeDataFile dsipm_3200_22.dat
/Rich/pmt/detection 0.98
/Rich/pmt/geomEfficiency 0.687
/Rich/pmt/pixelSize 3.5 mm
#/Rich/pmt/pixelSize 0 mm

/Rich/radiator/scatterLength 4.3 cm

/Rich/mode manual
/Rich/proximity 200 mm
/Rich/radiator/addLayer 1.0465  8.5 mm
/Rich/radiator/addLayer 1.0431    9 mm
/Rich/radiator/addLayer 1.0392    9 mm
/Rich/radiator/addLayer 1.036    11 mm

/Rich/update

