/run/verbose 2
/control/verbose 2
/analysis/verbose 2
/analysis/interactive off

# Invoke the OGLIX driver
/vis/open HepRepFile

/vis/scene/create
/vis/scene/add/volume
/vis/sceneHandler/attach
/vis/viewer/flush

#/vis/scene/add/trajectories
/vis/scene/add/hits

# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
/tracking/storeTrajectory 1

/vis/scene/endOfEventAction refresh
/vis/scene/endOfRunAction accumulate

/run/beamOn 2

